# Generated by Django 6.0.2 on 2026-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_medico_paciente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='numero_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='tipo_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='uf_conselho',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='upload_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos'),
        ),
        migrations.AddField(
            model_name='medico',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
