# Generated by Django 6.0.2 on 2026-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_especialidades_estados_tipo_conselho_medico_quarta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicas',
            name='celular',
            field=models.CharField(default='0000000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='celular2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18),
        ),
        migrations.AddField(
            model_name='clinicas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-12-12T00:00:00+0000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicas',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
