# Generated by Django 6.0.2 on 2026-02-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_clinicas_especialidades_medico_quarta_medico_quinta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_conselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='especialidades',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='especialidades',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='medico',
            name='tipo_conselho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='painel.tipo_conselho'),
        ),
    ]
