# Generated by Django 6.0.2 on 2026-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_clinicas_celular_clinicas_celular2_clinicas_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
