# Generated by Django 6.0.2 on 2026-02-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_tipo_conselho_remove_especialidades_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.estados'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.estados'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.estados'),
        ),
    ]
