# Generated by Django 6.0.2 on 2026-03-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_alter_especialidades_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='quarta',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='quinta',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='sexta',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='terca',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='quarta',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='quinta',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='sexta',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='terca',
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=10)),
                ('domingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domingo', to='painel.medico')),
                ('quarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarta', to='painel.medico')),
                ('quinta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quinta', to='painel.medico')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabado', to='painel.medico')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.salas')),
                ('segunda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segunda', to='painel.medico')),
                ('sexta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexta', to='painel.medico')),
                ('terca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terca', to='painel.medico')),
            ],
            options={
                'unique_together': {('sala', 'turno')},
            },
        ),
    ]
