# Generated by Django 6.0.2 on 2026-03-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_alter_vagas_domingo_alter_vagas_quarta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='sublocador',
        ),
    ]
