# Generated by Django 6.0.2 on 2026-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_alter_paciente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('especialidade', models.CharField(max_length=100)),
                ('role', models.CharField(default='medico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
