# Generated by Django 6.0.2 on 2026-03-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_remove_medico_quarta_remove_medico_quinta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='domingo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domingo', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='quarta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarta', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='quinta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quinta', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='sabado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabado', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segunda', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='sexta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexta', to='painel.medico'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='terca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terca', to='painel.medico'),
        ),
    ]
