# Generated by Django 6.0.2 on 2026-03-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_remove_salas_sublocador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='painel.especialidades'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='painel.estados'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numero_conselho',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rqe',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='uf_conselho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uf_conselho', to='painel.estados'),
        ),
    ]
