# Generated by Django 6.0.2 on 2026-03-13 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_alter_medico_especialidade_alter_medico_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='sabado',
        ),
        migrations.AddField(
            model_name='vagas',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='painel.clinicas'),
            preserve_default=False,
        ),
    ]
