# Generated by Django 6.0.2 on 2026-03-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0012_remove_vagas_domingo_remove_vagas_sabado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='hora_fim',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='max_pacientes',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='vagas',
            name='pacientes_atuais',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medico',
            name='celular',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.clinicas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.paciente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.salas')),
            ],
        ),
    ]
