# Generated by Django 6.0.2 on 2026-03-15 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0013_vagas_hora_fim_vagas_hora_inicio_vagas_max_pacientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='data_consulta',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
