# Generated by Django 6.0.2 on 2026-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_agendamentos_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='hora_fim',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
        ),
    ]
