[project]
name = "clinica-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.135.2",
    "passlib[bcrypt]>=1.7.4",
    "prometheus-client>=0.24.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.48",
    "structlog>=25.5.0",
    "supabase>=2.3.0",
    "python-multipart>=0.0.9",
    "filetype>=1.2.0",
    "pytest>=9.1.1",
    "httpx>=0.28.1",
    "pytest-mock>=3.15.1",
    "boto3>=1.43.47",
    "ruff>=0.16.0",
    "black>=26.5.1",
    "tzdata>=2024.1",
]

[tool.ruff.lint]
ignore = [
    "B008",  # Do not perform function call in argument defaults (aceito em FastAPI)
    "BLE001",  # Do not catch blind exception (se você quiser manter)
    "EXE002",  # The file is executable but no shebang is present
    "PLW0602",  # Using global variable but no assignment (aceito em testes)
]