name: web

on:
  workflow_dispatch:

jobs:
  test-web:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run Django tests
      run: uv run python src/clinica/manage.py test
    
    - name: Check Django migrations
      run: uv run python src/clinica/manage.py makemigrations --check
