
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        python manage.py migrate &&
        cd src/clinica &&
        python populate_db.py &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DEBUG=1
